//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationDemo.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationDemo.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balmy.
        /// </summary>
        public static string Balmy {
            get {
                return ResourceManager.GetString("Balmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracing.
        /// </summary>
        public static string Bracing {
            get {
                return ResourceManager.GetString("Bracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilly.
        /// </summary>
        public static string Chilly {
            get {
                return ResourceManager.GetString("Chilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        public static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        public static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current count:.
        /// </summary>
        public static string CurrentCount {
            get {
                return ResourceManager.GetString("CurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing.
        /// </summary>
        public static string Freezing {
            get {
                return ResourceManager.GetString("Freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string Hello__world_ {
            get {
                return ResourceManager.GetString("Hello, world!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component demonstrates showing data..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild.
        /// </summary>
        public static string Mild {
            get {
                return ResourceManager.GetString("Mild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorching.
        /// </summary>
        public static string Scorching {
            get {
                return ResourceManager.GetString("Scorching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweltering.
        /// </summary>
        public static string Sweltering {
            get {
                return ResourceManager.GetString("Sweltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (C).
        /// </summary>
        public static string TempC {
            get {
                return ResourceManager.GetString("TempC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (F).
        /// </summary>
        public static string TempF {
            get {
                return ResourceManager.GetString("TempF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        public static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
